// scripts/seed-build.ts — builds src/data/seed-words.ts from docs/example-words.md (`npm run seed:build`).
// Parses the table's columns (#, Greek lemma, Lvl, Lsn, English gloss, Part of speech, note) and keeps one
// entry per distinct lemma: the lemma as BMA shows it, the gloss, the lowest Lsn of its rows, the part of speech.
// Runs under plain node (type stripping), so it only uses erasable TypeScript.
import { readFileSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import type { SeedWord } from '../src/data/seedWord.ts';

/** The distinct lemmas of the md's table, in the order they first appear. */
export function parseExampleWords(md: string): SeedWord[] {
  const byLemma = new Map<string, SeedWord>();
  for (const line of md.split('\n')) {
    if (!line.startsWith('|')) continue;
    const cells = line.split('|').slice(1, -1).map((c) => c.trim());
    if (cells.length < 6 || !/^\d+$/.test(cells[0])) continue; // the header, the rule and prose
    const [, rawLemma, , lsn, gloss, pos] = cells;
    const lemma = rawLemma.normalize('NFC');
    const lesson = Number(lsn);
    const seen = byLemma.get(lemma);
    if (!seen) byLemma.set(lemma, { lemma, gloss, lesson, pos });
    else if (lesson < seen.lesson) seen.lesson = lesson;
  }
  return [...byLemma.values()];
}

const str = (s: string) => JSON.stringify(s);

/** The text of src/data/seed-words.ts for these words. */
export function renderSeed(words: SeedWord[]): string {
  const rows = words
    .map((w) => `  { lemma: ${str(w.lemma)}, gloss: ${str(w.gloss)}, lesson: ${w.lesson}, pos: ${str(w.pos)} },`)
    .join('\n');
  return `// An example word list (the owner's own BMA words, lessons 1-10); replace or extend it with Import.
// Generated by scripts/seed-build.ts from docs/example-words.md (npm run seed:build); do not edit by hand.
import type { SeedWord } from './seedWord';

export const SEED_WORDS: SeedWord[] = [
${rows}
];
`;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const md = readFileSync(new URL('../docs/example-words.md', import.meta.url), 'utf8');
  const words = parseExampleWords(md);
  writeFileSync(new URL('../src/data/seed-words.ts', import.meta.url), renderSeed(words));
  console.log(`src/data/seed-words.ts: ${words.length} words from docs/example-words.md`);
}
